#!/opt/sdr/perl/bin/perl

# COPYRIGHT: Copyright (c) 2013 System Data Recorder
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#  (http://www.gnu.org/copyleft/gpl.html)

# Built-in self-test SDR Recording Module

use strict;
use warnings;
use Getopt::Std;
use 5.010;

# Debug Only
#use Data::Dumper;

#
# Command line arguments
#
usage() if defined $ARGV[0] and $ARGV[0] eq "--help";
getopts('hr:cV') or usage();
usage()    if defined $main::opt_h;
revision() if defined $main::opt_V;


#
#  Variables
#
local $| = 1;



# ######### #
# MAIN BODY #
# ######### #

## store recorder list
my @recs;

## by default we process all main recorders
## if we use r option recsem turns true
my $recsem = 0;


## check for recorder list
if ( defined $main::opt_r ) {
    # check comma separator
    # /^(([a-z]*[0-9](:[1-9])?|,)*$)/
    usage() if $main::opt_r !~ /^(((sys|cpu|disk|nic|hdw)rec?|,)*$)/;
    $recsem = 1;
    @recs = split( /,/, $main::opt_r );
}
    


sub check_recorder {

    my @d;
    my $status = 0;


    # return status
    return $status;
}


# usage - print usage and exit.
sub usage {
    print STDERR <<END;
USAGE: sdrdroid [-hvV] [-r recorder[,recorder...] command
                [-s startime] [-e endtime]
OPTIONS:
  -h help                            # help information
  -v verbose                         # verbose
  -V revision                        # revision information
  -r recorder,recorder,...           # recorder list

COMMAND:
     bist                            # built-in selft-test
     run                             # run recorders
  
 eg, sdrdroid bist                   # self-test all recorders
     sdrdroid -r sysrec bist         # self-test sysrec
     sdrdroid -r sysrec,cpurec bist  # self-test sysrec,cpurec

NOTES:
sdrbist - SDR Built-In Self-Test procedure will test all
main recorders of SDR: sysrec, cpurec, diskrec, nicrec
and hdwrec. sdrbist will ensure the SDR Recording module
has been properly installed and is correctly configured.
END
    exit 0;
}


# revision - print revision and exit
sub revision {
    print STDERR <<END;
sdrbist: 0.75, 2013-12-31
END
    exit 0;
}
